// Documentation that derives from the corpus has to stay derived. A stale
// rule reference is worse than none: it tells a reader a class is covered
// when it is not.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { ROOT, allRules } from './helpers.mjs';
import { providerList } from '../scripts/lib/providers.js';

const DOCS = resolve(ROOT, 'docs');
const read = (f) => readFileSync(join(DOCS, f), 'utf8');
const docFiles = () => readdirSync(DOCS).filter((f) => f.endsWith('.md'));

test('every rule appears in the generated reference', () => {
  const rules = read('rules.md');
  const missing = allRules().map((r) => r.id).filter((id) => !rules.includes(`\`${id}\``));
  assert.deepEqual(missing, []);
});

test('the reference reports the real counts', () => {
  const rules = allRules();
  const text = read('rules.md');
  assert.match(text, new RegExp(`${rules.length} rules across`));
  assert.match(text, new RegExp(`${rules.filter((r) => r.tier === 'immediate').length} are in the immediate tier`));
});

test('generated docs are current', () => {
  // The same gate CI runs. Regenerating and comparing is the only check that
  // cannot itself drift.
  const before = Object.fromEntries(docFiles().map((f) => [f, read(f)]));
  const r = spawnSync(process.execPath, [resolve(ROOT, 'scripts/build-docs.mjs')], { encoding: 'utf8' });
  assert.equal(r.status, 0, r.stderr);
  const stale = docFiles().filter((f) => before[f] !== undefined && before[f] !== read(f));
  assert.deepEqual(stale, [], 'run: npm run build:docs');
});

test('generated docs say they are generated', () => {
  for (const f of ['rules.md', 'commands.md', 'harnesses.md', 'severity.md']) {
    assert.match(read(f), /^<!-- GENERATED by/, `${f} must warn against hand-editing`);
  }
});

test('hand-written docs are not marked generated', () => {
  for (const f of ['README.md', 'getting-started.md', 'waivers.md', 'ci.md', 'architecture.md', 'controls.md', 'findings-store.md']) {
    assert.ok(existsSync(join(DOCS, f)), `missing ${f}`);
    assert.ok(!read(f).startsWith('<!-- GENERATED'), `${f} would be overwritten by the generator`);
  }
});

test('every harness is listed with its confidence tier', () => {
  const text = read('harnesses.md');
  for (const p of providerList()) {
    assert.ok(text.includes(`\`${p.configDir}\``), `harnesses.md omits ${p.configDir}`);
  }
  // The tiers are the honest part: a skill that silently fails to load looks
  // exactly like a skill that found nothing.
  for (const heading of ['## Verified', '## Documented', '## Convention']) {
    assert.ok(text.includes(heading), `harnesses.md omits ${heading}`);
  }
});

test('every relative link across the docs resolves', () => {
  const broken = [];
  for (const f of docFiles()) {
    for (const [, , target] of read(f).matchAll(/\[([^\]]+)\]\((?!https?:)([^)#]+)(?:#[^)]*)?\)/g)) {
      if (!existsSync(resolve(DOCS, target))) broken.push(`docs/${f} -> ${target}`);
    }
  }
  assert.deepEqual(broken, []);
});

test('the demo golden matches a live run', () => {
  const r = spawnSync(process.execPath, [resolve(ROOT, 'scripts/demo.mjs'), '--check'], { encoding: 'utf8' });
  assert.equal(r.status, 0, `${r.stdout}${r.stderr}`);
});

test('the demo README quotes the golden, not remembered numbers', () => {
  const golden = readFileSync(resolve(ROOT, 'demo/expected-findings.txt'), 'utf8');
  const readme = readFileSync(resolve(ROOT, 'demo/README.md'), 'utf8');
  for (const key of ['total findings:', 'distinct rules:', 'by priority:', 'by pack:']) {
    const line = golden.split('\n').find((l) => l.startsWith(key));
    assert.ok(readme.includes(line), `demo/README.md is stale: "${line}"`);
  }
});

test('the demo exercises every pack', () => {
  // A demo that misses a pack silently stops demonstrating it.
  const golden = readFileSync(resolve(ROOT, 'demo/expected-findings.txt'), 'utf8');
  const packs = new Set(allRules().map((r) => r.pack));
  const line = golden.split('\n').find((l) => l.startsWith('by pack:'));
  for (const pack of packs) {
    assert.match(line, new RegExp(`\\b${pack}=`), `the demo triggers no ${pack} rules`);
  }
});

test('the demo is excluded from the self-scan but not from itself', () => {
  const config = JSON.parse(readFileSync(resolve(ROOT, '.airtight/config.json'), 'utf8'));
  assert.ok(config.detector.ignoreFiles.some((g) => g.startsWith('demo/')),
    'a deliberately vulnerable demo must not fail our own self-scan');
  // ...and the runner passes --no-config so the demo still reports everything.
  assert.match(readFileSync(resolve(ROOT, 'scripts/demo.mjs'), 'utf8'), /'--no-config'/);
});
