// Lockfile parsing, lockfile detection, and OSV advisory querying tests.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseLockfile, detectLockfiles } from '../engine/src/lockfile.mjs';
import { queryOsv } from '../engine/src/osv.mjs';

test('parseLockfile parses npm v1 package-lock.json', () => {
  const content = JSON.stringify({
    name: 'v1-app',
    version: '1.0.0',
    lockfileVersion: 1,
    dependencies: {
      lodash: {
        version: '4.17.20',
      },
      express: {
        version: '4.18.2',
        dependencies: {
          debug: {
            version: '2.6.9',
          },
        },
      },
    },
  });

  const res = parseLockfile('package-lock.json', content);
  assert.equal(res.dependencies.length, 3);
  assert.deepEqual(res.dependencies[0], {
    name: 'lodash',
    version: '4.17.20',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'express',
    version: '4.18.2',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
  assert.deepEqual(res.dependencies[2], {
    name: 'debug',
    version: '2.6.9',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
});

test('parseLockfile parses npm v2/v3 package-lock.json', () => {
  const content = JSON.stringify({
    name: 'v3-app',
    version: '1.0.0',
    lockfileVersion: 3,
    packages: {
      '': {
        name: 'v3-app',
        version: '1.0.0',
      },
      'node_modules/lodash': {
        version: '4.17.21',
      },
      'node_modules/@babel/core': {
        version: '7.22.5',
      },
      'node_modules/express/node_modules/debug': {
        version: '2.6.9',
      },
    },
  });

  const res = parseLockfile('package-lock.json', content);
  assert.equal(res.dependencies.length, 3);
  assert.deepEqual(res.dependencies.find((d) => d.name === 'lodash'), {
    name: 'lodash',
    version: '4.17.21',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
  assert.deepEqual(res.dependencies.find((d) => d.name === '@babel/core'), {
    name: '@babel/core',
    version: '7.22.5',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
  assert.deepEqual(res.dependencies.find((d) => d.name === 'debug'), {
    name: 'debug',
    version: '2.6.9',
    ecosystem: 'npm',
    lockfile: 'package-lock.json',
  });
});

test('parseLockfile parses yarn v1 classic lockfiles', () => {
  const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.5.5":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz"

lodash@^4.17.15, lodash@^4.17.19:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`;

  const res = parseLockfile('yarn.lock', content);
  assert.equal(res.dependencies.length, 2);
  assert.deepEqual(res.dependencies[0], {
    name: '@babel/code-frame',
    version: '7.12.11',
    ecosystem: 'npm',
    lockfile: 'yarn.lock',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'lodash',
    version: '4.17.21',
    ecosystem: 'npm',
    lockfile: 'yarn.lock',
  });
});

test('parseLockfile parses yarn v2 Berry lockfiles', () => {
  const content = `__metadata:
  version: 6
  cacheKey: 8

"@babel/code-frame@npm:^7.0.0":
  version: 7.12.11
  resolution: "@babel/code-frame@npm:7.12.11"

"lodash@npm:^4.17.15":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
`;

  const res = parseLockfile('yarn.lock', content);
  assert.equal(res.dependencies.length, 2);
  assert.deepEqual(res.dependencies[0], {
    name: '@babel/code-frame',
    version: '7.12.11',
    ecosystem: 'npm',
    lockfile: 'yarn.lock',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'lodash',
    version: '4.17.21',
    ecosystem: 'npm',
    lockfile: 'yarn.lock',
  });
});

test('parseLockfile parses pnpm-lock.yaml across format versions', () => {
  const v5 = `lockfileVersion: 5.4
packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-test}
  /@babel/core/7.12.10:
    resolution: {integrity: sha512-test}
`;
  const res5 = parseLockfile('pnpm-lock.yaml', v5);
  assert.equal(res5.dependencies.length, 2);
  assert.deepEqual(res5.dependencies[0], {
    name: 'lodash',
    version: '4.17.21',
    ecosystem: 'npm',
    lockfile: 'pnpm-lock.yaml',
  });
  assert.deepEqual(res5.dependencies[1], {
    name: '@babel/core',
    version: '7.12.10',
    ecosystem: 'npm',
    lockfile: 'pnpm-lock.yaml',
  });

  const v6 = `lockfileVersion: '6.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-test}
  /@babel/core@7.12.10:
    resolution: {integrity: sha512-test}
`;
  const res6 = parseLockfile('pnpm-lock.yaml', v6);
  assert.equal(res6.dependencies.length, 2);
  assert.equal(res6.dependencies[0].name, 'lodash');
  assert.equal(res6.dependencies[0].version, '4.17.21');

  const v9 = `lockfileVersion: '9.0'
packages:
  'lodash@4.17.21(react@17.0.2)':
    resolution: {integrity: sha512-test}
`;
  const res9 = parseLockfile('pnpm-lock.yaml', v9);
  assert.equal(res9.dependencies.length, 1);
  assert.equal(res9.dependencies[0].name, 'lodash');
  assert.equal(res9.dependencies[0].version, '4.17.21');
});

test('parseLockfile parses Cargo.lock TOML package blocks', () => {
  const content = `# Generated by Cargo
version = 3

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873e1b9b056a4dc4c0c198b24c3efa05996677773826000eee6a3154f1a"

[[package]]
name = "syn"
version = "2.0.48"
source = "registry+https://github.com/rust-lang/crates.io-index"
`;

  const res = parseLockfile('Cargo.lock', content);
  assert.equal(res.dependencies.length, 2);
  assert.deepEqual(res.dependencies[0], {
    name: 'serde',
    version: '1.0.197',
    ecosystem: 'crates.io',
    lockfile: 'Cargo.lock',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'syn',
    version: '2.0.48',
    ecosystem: 'crates.io',
    lockfile: 'Cargo.lock',
  });
});

test('parseLockfile parses go.sum skipping /go.mod and removing leading v', () => {
  const content = `github.com/gin-gonic/gin v1.9.1 h1:4+fr/ElT2H2jSXnEQsiL113YKaWmAuUcpbcu401/OBY=
github.com/gin-gonic/gin v1.9.1/go.mod h1:hChLIG8zxokcGpt25GwHtxGPRslSu64234056j68PcY=
golang.org/x/crypto v0.14.0 h1:wBqRN2Lt1De511zu80ux1s0T8Lp85z3T26q+Kmh189k=
golang.org/x/crypto v0.14.0/go.mod h1:MVFd36Yz2pdRlwP9SVn/smS55eS2jcPrb+nld5/4yP8=
`;

  const res = parseLockfile('go.sum', content);
  assert.equal(res.dependencies.length, 2);
  assert.deepEqual(res.dependencies[0], {
    name: 'github.com/gin-gonic/gin',
    version: '1.9.1',
    ecosystem: 'Go',
    lockfile: 'go.sum',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'golang.org/x/crypto',
    version: '0.14.0',
    ecosystem: 'Go',
    lockfile: 'go.sum',
  });
});

test('parseLockfile parses requirements.txt extracting pinned dependencies', () => {
  const content = `# Python requirements
--extra-index-url https://pypi.org/simple
-r other-requirements.txt

requests==2.31.0
urllib3 == 1.26.5
flask===2.0.1
# Unpinned package should be ignored:
pytest>=7.0.0
`;

  const res = parseLockfile('requirements.txt', content);
  assert.equal(res.dependencies.length, 3);
  assert.deepEqual(res.dependencies[0], {
    name: 'requests',
    version: '2.31.0',
    ecosystem: 'PyPI',
    lockfile: 'requirements.txt',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'urllib3',
    version: '1.26.5',
    ecosystem: 'PyPI',
    lockfile: 'requirements.txt',
  });
  assert.deepEqual(res.dependencies[2], {
    name: 'flask',
    version: '2.0.1',
    ecosystem: 'PyPI',
    lockfile: 'requirements.txt',
  });
});

test('parseLockfile parses poetry.lock TOML package blocks', () => {
  const content = `[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"

[[package]]
name = "urllib3"
version = "1.26.5"
description = "HTTP library with thread-safe connection pooling."
optional = false
`;

  const res = parseLockfile('poetry.lock', content);
  assert.equal(res.dependencies.length, 2);
  assert.deepEqual(res.dependencies[0], {
    name: 'requests',
    version: '2.31.0',
    ecosystem: 'PyPI',
    lockfile: 'poetry.lock',
  });
  assert.deepEqual(res.dependencies[1], {
    name: 'urllib3',
    version: '1.26.5',
    ecosystem: 'PyPI',
    lockfile: 'poetry.lock',
  });
});

test('parseLockfile fails open on corrupt syntax and unknown formats', () => {
  assert.deepEqual(parseLockfile('package-lock.json', '{ corrupt json : true }'), { dependencies: [] });
  assert.deepEqual(parseLockfile('pnpm-lock.yaml', '::: malformed ::: yaml'), { dependencies: [] });
  assert.deepEqual(parseLockfile('unknown.xyz', 'some content'), { dependencies: [] });
  assert.deepEqual(parseLockfile('/nonexistent/path/package-lock.json'), { dependencies: [] });
});

test('detectLockfiles finds lockfiles and ignores skip directories', () => {
  const tmp = mkdtempSync(join(tmpdir(), 'airtight-detect-'));
  try {
    writeFileSync(join(tmp, 'package-lock.json'), '{}');
    writeFileSync(join(tmp, 'Cargo.lock'), '');

    mkdirSync(join(tmp, 'subpkg'));
    writeFileSync(join(tmp, 'subpkg', 'yarn.lock'), '');

    // Ignored directories
    mkdirSync(join(tmp, 'node_modules'));
    writeFileSync(join(tmp, 'node_modules', 'package-lock.json'), '{}');
    mkdirSync(join(tmp, '.git'));
    writeFileSync(join(tmp, '.git', 'Cargo.lock'), '');

    const detected = detectLockfiles(tmp);
    const basenames = detected.map((p) => p.replace(tmp + '/', '')).sort();
    assert.deepEqual(basenames, ['Cargo.lock', 'package-lock.json', 'subpkg/yarn.lock']);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('detectLockfiles fails open on nonexistent root', () => {
  assert.deepEqual(detectLockfiles('/nonexistent/directory/test'), []);
});

test('queryOsv maps advisories to Airtight finding shape', async () => {
  const tmp = mkdtempSync(join(tmpdir(), 'airtight-osv-'));
  const cacheFile = join(tmp, 'osv.json');

  const sampleVuln = {
    id: 'GHSA-p6mc-m468-83gw',
    summary: 'Prototype pollution in lodash',
    details: 'Versions of lodash prior to 4.17.21 are vulnerable to prototype pollution.',
    database_specific: {
      severity: 'HIGH',
      cwe_ids: ['CWE-1321'],
    },
    affected: [
      {
        package: { name: 'lodash', ecosystem: 'npm' },
        ranges: [
          {
            type: 'SEMVER',
            events: [{ introduced: '0' }, { fixed: '4.17.21' }],
          },
        ],
      },
    ],
  };

  writeFileSync(cacheFile, JSON.stringify({
    'npm:lodash@4.17.20': [sampleVuln],
  }));

  try {
    const deps = [
      { name: 'lodash', version: '4.17.20', ecosystem: 'npm', lockfile: 'package-lock.json' },
    ];

    const findings = await queryOsv(deps, { cacheDir: tmp, offline: true });
    assert.equal(findings.length, 1);

    const f = findings[0];
    assert.equal(f.rule, 'dep/npm-advisory');
    assert.equal(f.severity, 'high');
    assert.equal(f.confidence, 'confirmed');
    assert.equal(f.priority, 'P1');
    assert.equal(f.cwe, 'CWE-1321');
    assert.equal(f.message, 'Prototype pollution in lodash');
    assert.equal(f.fix, '4.17.21');
    assert.equal(f.file, 'package-lock.json');
    assert.match(f.id, /^[0-9a-f]{12}$/);
    assert.equal(f.package.name, 'lodash');
    assert.equal(f.package.version, '4.17.20');
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('queryOsv batches requests up to 100 and caches responses', async () => {
  const tmp = mkdtempSync(join(tmpdir(), 'airtight-osv-batch-'));
  const originalFetch = globalThis.fetch;
  const batchesReceived = [];

  globalThis.fetch = async (url, opts) => {
    const body = JSON.parse(opts.body);
    batchesReceived.push(body.queries);
    return {
      ok: true,
      json: async () => ({
        results: body.queries.map((q) => {
          if (q.package.name === 'vuln-pkg') {
            return {
              vulns: [
                {
                  id: 'VULN-001',
                  summary: 'Sample vulnerability',
                  database_specific: { severity: 'CRITICAL', cwe_ids: ['CWE-79'] },
                  affected: [{ ranges: [{ events: [{ fixed: '2.0.0' }] }] }],
                },
              ],
            };
          }
          return {};
        }),
      }),
    };
  };

  try {
    const deps = [];
    for (let i = 0; i < 150; i++) {
      deps.push({
        name: i === 5 ? 'vuln-pkg' : `safe-pkg-${i}`,
        version: '1.0.0',
        ecosystem: 'npm',
        lockfile: 'package-lock.json',
      });
    }

    const findings = await queryOsv(deps, { cacheDir: tmp, offline: false });
    assert.equal(batchesReceived.length, 2);
    assert.equal(batchesReceived[0].length, 100);
    assert.equal(batchesReceived[1].length, 50);

    assert.equal(findings.length, 1);
    assert.equal(findings[0].severity, 'critical');
    assert.equal(findings[0].priority, 'P0');
    assert.equal(findings[0].cwe, 'CWE-79');
    assert.equal(findings[0].fix, '2.0.0');

    // Verify cache file was written to disk
    const cacheOnDisk = JSON.parse(readFileSync(join(tmp, 'osv.json'), 'utf8'));
    assert.ok('npm:vuln-pkg@1.0.0' in cacheOnDisk);
    assert.equal(cacheOnDisk['npm:vuln-pkg@1.0.0'].length, 1);

    // Run again with offline = true; it should read from disk without network
    const offlineFindings = await queryOsv(deps, { cacheDir: tmp, offline: true });
    assert.equal(offlineFindings.length, 1);
    assert.equal(offlineFindings[0].id, findings[0].id);
  } finally {
    globalThis.fetch = originalFetch;
    rmSync(tmp, { recursive: true, force: true });
  }
});

test('queryOsv fails open on network failure and timeout', async () => {
  const tmp = mkdtempSync(join(tmpdir(), 'airtight-osv-fail-'));
  const originalFetch = globalThis.fetch;

  globalThis.fetch = async () => {
    throw new Error('Network error ENOTFOUND api.osv.dev');
  };

  try {
    const deps = [
      { name: 'lodash', version: '4.17.20', ecosystem: 'npm', lockfile: 'package-lock.json' },
    ];

    // Must not throw error, returns empty results
    const findings = await queryOsv(deps, { cacheDir: tmp, offline: false, timeoutMs: 50 });
    assert.deepEqual(findings, []);
  } finally {
    globalThis.fetch = originalFetch;
    rmSync(tmp, { recursive: true, force: true });
  }
});
