FROM golang:1.22 AS builder
WORKDIR /src
COPY . .
RUN go build -o /bin/app

FROM alpine:3.20
COPY --from=builder /bin/app /bin/app
HEALTHCHECK --interval=1m CMD /bin/app status || exit 1
CMD ["/bin/app"]
