FROM alpine:3.20
ADD https://example.com/one.tar.gz /tmp/one.tar.gz
ADD https://example.com/two.sh /tmp/two.sh
ADD http://example.com/three.bin /usr/local/bin/three
ADD --chown=root:root https://example.com/four.zip /tmp/four.zip
USER nobody
