// Specification for the credential-shaped fixture corpora.
//
// Why this exists rather than plain files: a repository containing real-shaped
// provider tokens gets blocked by secret-scanning push protection, and asking
// people to allowlist secrets in order to clone a security tool is a poor
// first impression. Formats with a checksum (AWS, GitHub, npm, Google) are
// ignored by scanners when the checksum fails, but GitLab, SendGrid, Stripe
// and Slack have none, so any valid-shaped value is indistinguishable from a
// live one.
//
// The materialized corpora are generated by scripts/gen-secrets.mjs and
// gitignored. This file is the reviewable artifact: it shows every line shape,
// which is easier to audit than thirty files of near-identical text.
//
// `g` provides deterministic generators. Values are stable across runs so the
// fixture suite and the demo golden do not churn.

export const corpora = {
  'secret/gitlab-token': {
    flag: (g) => [
      `GITLAB_TOKEN=${g.gitlab()}`,
      `const t = "${g.gitlab()}";`,
      `  token: ${g.gitlab()}`,
      `curl -H "PRIVATE-TOKEN: ${g.gitlab()}" https://gitlab.com/api/v4/user`,
    ],
    pass: (g) => [
      'GITLAB_TOKEN=glpat-YOUR_TOKEN',
      'glpat-short',
      '# rotate the glpat- token quarterly',
      'GITLAB_TOKEN=${CI_JOB_TOKEN}',
      // Valid-shaped on purpose, to exercise the PLACEHOLDER gate. Generated
      // rather than literal so this file carries no token either.
      `PLACEHOLDER ${g.gitlab()}`,
    ],
  },

  'secret/sendgrid-key': {
    flag: (g) => [
      `SENDGRID_API_KEY=${g.sendgrid()}`,
      `sg.set_api_key("${g.sendgrid()}")`,
      `  sendgrid: ${g.sendgrid()}`,
      `const k = '${g.sendgrid()}';`,
    ],
    pass: () => [
      'SENDGRID_API_KEY=SG.YOUR_KEY_HERE',
      'SG.short.key',
      '# SendGrid keys start with SG.',
      'SENDGRID_API_KEY=${SENDGRID_API_KEY}',
      'PLACEHOLDER SG.abcdefghijklmnopqrstuv.abcdefghijklmnopqrstuvwxyz0123456789ABCDEF',
    ],
  },

  'secret/stripe-live-key': {
    flag: (g) => [
      `STRIPE_SECRET_KEY=${g.stripe('sk')}`,
      `const stripe = require("stripe")("${g.stripe('sk')}");`,
      `  restricted: ${g.stripe('rk')}`,
      `"stripe_key": "${g.stripe('sk')}"`,
    ],
    pass: () => [
      'STRIPE_SECRET_KEY=sk_test_51H8xKvLmNoPqRsTuVwXyZaBc',
      'STRIPE_SECRET_KEY=sk_live_YOUR_KEY',
      'pk_live_51H8xKvLmNoPqRsTuVwXyZaBc',
      '// never commit an sk_live_ key',
      'PLACEHOLDER sk_live_51H8xKvLmNoPqRsTu',
    ],
  },

  'secret/slack-token': {
    flag: (g) => [
      `SLACK_BOT_TOKEN=${g.slack('b')}`,
      `const t = "${g.slack('p')}";`,
      `  slack_token: ${g.slack('a')}`,
      `client = WebClient(token="${g.slack('s')}")`,
    ],
    pass: (g) => [
      'SLACK_BOT_TOKEN=xoxb-YOUR_TOKEN_HERE',
      'xoxb-short',
      '// tokens start with xoxb- or xoxp-',
      'SLACK_TOKEN=${{ secrets.SLACK }}',
      `PLACEHOLDER ${g.slack('b')}`,
    ],
  },
  'secret/aws-access-key-id': {
    flag: (g) => [
      `const key = "${g.aws('AKIA')}";`,
      `AWS_ACCESS_KEY_ID=${g.aws('AKIA')}`,
      `  aws_access_key_id: ${g.aws('ASIA')}`,
      `boto3.client("s3", aws_access_key_id="${g.aws('ABIA')}")`,
      `<AccessKeyId>${g.aws('ACCA')}</AccessKeyId>`,
    ],
    pass: () => [
      'const key = "AKIA_EXAMPLE_NOT_A_KEY";',
      'AWS_ACCESS_KEY_ID=YOUR_KEY_HERE',
      'akia_lowercase_is_not_a_key_at_all_here',
      'const AKIASHORT = "AKIA123";',
      '// Set AKIA... in the environment, never in code',
    ],
  },

  'secret/aws-secret-access-key': {
    flag: (g) => [
      `aws_secret_access_key = "${g.b64(40)}"`,
      `AWS_SECRET_ACCESS_KEY=${g.b64(40)}`,
      `awsSecretAccessKey: '${g.b64(40)}'`,
      `"aws_secret_access_key": "${g.b64(40)}"`,
    ],
    pass: () => [
      'aws_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"',
      'AWS_SECRET_ACCESS_KEY=YOUR_SECRET_HERE',
      'aws_secret_access_key = ""',
      'const notASecret = "short";',
      '# aws_secret_access_key is read from the instance role',
    ],
  },

  'secret/github-token': {
    flag: (g) => [
      `const token = "${g.gh('ghp')}";`,
      `GITHUB_TOKEN=${g.gh('gho')}`,
      `Authorization: token ${g.gh('ghs')}`,
      `url = f"https://${g.gh('ghu')}@github.com/o/r.git"`,
      `pat: ${g.ghPat()}`,
    ],
    pass: () => [
      'const token = "ghp_YOUR_TOKEN_HERE";',
      'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}',
      'ghp_tooshort',
      '// Store the ghp_ prefixed token in a secret manager',
      'github_pat_PLACEHOLDER',
    ],
  },

  'secret/google-api-key': {
    flag: (g) => [
      `GOOGLE_API_KEY=${g.google()}`,
      `const key = "${g.google()}";`,
      `  maps_key: ${g.google()}`,
      `<meta name="google-api-key" content="${g.google()}">`,
    ],
    pass: () => [
      'GOOGLE_API_KEY=AIzaYOUR_KEY_HERE_PLACEHOLDER_000',
      'AIzaShort',
      '# Google keys begin with AIza',
      'GOOGLE_API_KEY=${GOOGLE_API_KEY}',
      'const example = "AIzaSyYOUR-EXAMPLE-KEY-GOES-HERE1234";',
    ],
  },

  'secret/npm-token': {
    flag: (g) => [
      `//registry.npmjs.org/:_authToken=${g.npm()}`,
      `NPM_TOKEN=${g.npm()}`,
      `  npmToken: ${g.npm()}`,
      `const t = "${g.npm()}";`,
    ],
    pass: () => [
      'NPM_TOKEN=npm_YOUR_TOKEN_HERE',
      'npm_short',
      '# tokens look like npm_ followed by 36 chars',
      '//registry.npmjs.org/:_authToken=${NPM_TOKEN}',
      'PLACEHOLDER npm_abcdefghijk',
    ],
  },

  'secret/anthropic-key': {
    flag: (g) => [
      `ANTHROPIC_API_KEY=${g.anthropic()}`,
      `client = Anthropic(api_key="${g.anthropic()}")`,
      `  anthropic_key: ${g.anthropic()}`,
      `const k = '${g.anthropic()}';`,
    ],
    pass: () => [
      'ANTHROPIC_API_KEY=sk-ant-YOUR_KEY_HERE',
      'sk-ant-short',
      '# keys are prefixed sk-ant-',
      'ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}',
      'PLACEHOLDER sk-ant-api03-abc',
    ],
  },

  'secret/openai-key': {
    flag: (g) => [
      `OPENAI_API_KEY=${g.openai('proj')}`,
      `openai.api_key = "${g.openai('svcacct')}"`,
      `  key: ${g.openai('admin')}`,
      `const k = '${g.openai('proj')}';`,
    ],
    pass: () => [
      'OPENAI_API_KEY=sk-proj-YOUR_KEY_HERE',
      'sk-proj-short',
      '# set OPENAI_API_KEY in the environment',
      'OPENAI_API_KEY=${{ secrets.OPENAI }}',
      'PLACEHOLDER sk-proj-abcdef',
    ],
  },

  'secret/jwt-with-claims': {
    flag: (g) => [
      `Authorization: Bearer ${g.jwt()}`,
      `const token = "${g.jwt()}";`,
      `  id_token: ${g.jwt()}`,
      `SESSION=${g.jwt()}`,
    ],
    pass: () => [
      'const token = "eyJhbGc.short.sig";',
      'Authorization: Bearer ${TOKEN}',
      '// a JWT has three base64url segments',
      'JWT_SECRET=${JWT_SECRET}',
      'const header = "eyJhbGciOiJIUzI1NiJ9";',
    ],
  },

  'dep/npm-auth-token-committed': {
    flag: (g) => [
      `//registry.npmjs.org/:_authToken=${g.npm()}`,
      `_auth=${g.b64(24)}=`,
      `npmAuthToken: "yarn_${g.b64(32)}"`,
      `//npm.pkg.github.com/:_authToken=${g.gh('ghp')}`,
    ],
    pass: () => [
      '//registry.npmjs.org/:_authToken=${NPM_TOKEN}',
      '_auth=${NPM_AUTH}',
      'npmAuthToken: "${YARN_TOKEN}"',
      'registry=https://registry.npmjs.org/',
      'always-auth=true',
      '# tokens come from CI secrets, never this file',
    ],
    file: '.npmrc',
  },

  'terraform/lambda-env-secret': {
    flag: (g) => [
      'resource "aws_lambda_function" "a" {',
      '  environment {', '    variables = {',
      `      API_KEY = "ak-abc123def456"`,
      '    }', '  }', '}',
      'resource "aws_lambda_function" "b" {',
      '  environment {', '    variables = {',
      '      DB_PASSWORD = "hunter2hunter2"',
      '    }', '  }', '}',
      'resource "aws_lambda_function" "c" {',
      '  environment {', '    variables = {',
      '      SECRET_TOKEN = "tok-9f8e7d6c5b4a"',
      '    }', '  }', '}',
      'resource "aws_lambda_function" "d" {',
      '  environment {', '    variables = {',
      `      ACCESS_KEY = "${g.aws()}"`,
      '    }', '  }', '}',
    ],
    pass: () => [
      'resource "aws_lambda_function" "a" {',
      '  environment {', '    variables = {',
      '      API_KEY = var.api_key',
      '      DB_PASSWORD = data.aws_secretsmanager_secret_version.db.secret_string',
      '      SECRET_ARN = aws_secretsmanager_secret.s.arn',
      '      LOG_LEVEL = "info"',
      '      TOKEN = local.token',
      '    }', '  }', '}',
    ],
    file: 'main.tf',
  },
};

/**
 * Demo files whose committed form would carry a live-shaped token. Their
 * templates live in demo/templates/, outside the scanned application, because
 * Dockerfile.tmpl matches `**''/Dockerfile*` and would otherwise be scanned
 * alongside the file it generates.
 */
export const demoTemplates = ['src/config.js', 'Dockerfile'];
