#!/usr/bin/env node
// Generate the reference documentation that must never go stale.
//
// A hand-written rule reference is wrong the day someone adds a rule, and a
// wrong security reference is worse than none: it tells a reader a class is
// covered when it is not. Everything derivable is derived.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileAll } from '../engine/src/rules.mjs';
import { SEVERITIES, CONFIDENCES, priorityOf, SLA_DAYS } from '../engine/src/findings.mjs';
import { providerList, placeholdersFor } from './lib/providers.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const GENERATED = '<!-- GENERATED by scripts/build-docs.mjs. Do not edit; edit the source it derives from. -->';

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const write = (name, body) => {
  mkdirSync(DOCS, { recursive: true });
  writeFileSync(join(DOCS, name), `${GENERATED}\n\n${body.trimEnd()}\n`);
};

const PACK_TITLES = {
  secret: 'Secrets and credentials',
  container: 'Containers',
  ci: 'CI and build pipeline',
  dep: 'Dependencies and supply chain',
  terraform: 'Terraform',
  k8s: 'Kubernetes',
  js: 'JavaScript and TypeScript',
  py: 'Python',
  go: 'Go',
  java: 'Java',
  rust: 'Rust',
};

const TIER_NOTE = {
  immediate: 'fires on edit',
  deep: 'end of turn',
};

function rulesDoc(rules) {
  const byPack = new Map();
  for (const r of rules) {
    if (!byPack.has(r.pack)) byPack.set(r.pack, []);
    byPack.get(r.pack).push(r);
  }

  const out = [
    '# Rule reference',
    '',
    `${rules.length} rules across ${byPack.size} packs. `
      + `${rules.filter((r) => r.tier === 'immediate').length} are in the immediate tier, meaning the edit `
      + 'hook may interrupt you with them; the rest run at the end of a turn.',
    '',
    'Every rule carries a severity and an independent **confidence**. Priority is derived from the pair '
      + 'and is never authored, which is why a `tentative` finding is never P0. See '
      + '[the severity model](severity.md).',
    '',
    '## Packs',
    '',
    '| Pack | Rules | Immediate | Covers |',
    '|---|---:|---:|---|',
  ];

  for (const [pack, list] of [...byPack].sort()) {
    out.push(`| [\`${pack}\`](#${pack}) | ${list.length} | ${list.filter((r) => r.tier === 'immediate').length} | ${PACK_TITLES[pack] ?? pack} |`);
  }

  for (const [pack, list] of [...byPack].sort()) {
    out.push('', `## ${pack}`, '', `${PACK_TITLES[pack] ?? pack}. ${list.length} rules.`, '');
    for (const r of list.sort((a, b) => a.id.localeCompare(b.id))) {
      const tags = [
        `**${r.severity}** / ${r.confidence}`,
        `\`${priorityOf(r.severity, r.confidence)}\``,
        r.cwe,
        r.owasp,
        TIER_NOTE[r.tier],
      ].filter(Boolean).join(' · ');

      out.push(`### \`${r.id}\``, '', `${r.name}`, '', tags, '', r.why.trim(), '', `**Fix.** ${r.fix.trim()}`, '');
      out.push(`<sub>Waive: \`airtight hooks ignore-value ${r.id} "<value>" --reason "<who decided: evidence>"\`, `
        + `or inline: \`airtight-disable-next-line ${r.id} -- <reason>\`</sub>`, '');
    }
  }
  return out.join('\n');
}

function commandsDoc(meta, skillSrc) {
  const rows = [...skillSrc.matchAll(/^\| `([a-z-]+)([^`]*)` \| (\w+) \| ([^|]+) \| \[[^\]]+\]\(reference\/([^)]+)\) \|$/gm)];
  const out = [
    '# Commands',
    '',
    `${rows.length} commands in three categories. Each has a playbook the model loads on demand; `
      + 'the playbooks are the actual behaviour, and they live in '
      + '[`skill/reference/`](../skill/reference/).',
    '',
  ];

  for (const category of ['Establish', 'Evaluate', 'Fix']) {
    const inCat = rows.filter(([, , , c]) => c === category);
    if (!inCat.length) continue;
    out.push(`## ${category}`, '');
    for (const [, name, args, , summary, ref] of inCat) {
      out.push(`### \`/airtight ${name}${args}\``, '', summary.trim(), '');
      const m = meta[name];
      if (m) out.push(`*When to use:* ${m.description.replace(/^[^.]*\.\s*/, '')}`, '');
      out.push(`[Playbook](../skill/reference/${ref})`, '');
    }
  }

  out.push('## Infrastructure verbs', '',
    'Not commands the model routes to, but things you run:', '',
    '```bash',
    'airtight hooks on | off | status',
    'airtight hooks ignore-value <rule> "<value>" --reason "..."',
    'airtight detect [paths] [--json] [--tier immediate] [--pack <name>] [--baseline <path>] [--since <ref>]',
    'airtight findings sync | list | accept | overdue',
    'airtight controls verify | coverage --framework <name>',
    'airtight context',
    '```', '',
    'Exit codes are the contract: `0` clean, `1` the engine failed, `2` findings present or a control failing.');
  return out.join('\n');
}

function harnessesDoc() {
  const tiers = {
    yes: ['Verified', 'Conventions confirmed against the real harness.'],
    documented: ['Documented', 'Taken from the harness’s published docs, not run end to end here. Report anything that does not work.'],
    convention: ['Convention', 'Follows the common `<dir>/skills/<name>/` layout; nothing harness-specific is known. These ship plain markdown and no hooks, because a frontmatter key a loader rejects breaks the whole skill while one it ignores costs nothing.'],
  };

  const out = [
    '# Harnesses',
    '',
    `Airtight installs into ${providerList().length} harnesses. Install with:`,
    '',
    '```bash',
    'npx airtight-security install                      # detects what you have',
    'npx airtight-security install --providers=cursor   # or name them',
    '```',
    '',
    'Confidence is recorded per harness rather than implied. It matters: a skill that '
      + 'silently fails to load looks exactly like a skill that found nothing.',
    '',
  ];

  for (const [tier, [title, note]] of Object.entries(tiers)) {
    const list = providerList().filter((p) => p.verified === tier);
    if (!list.length) continue;
    out.push(`## ${title}`, '', note, '',
      '| Harness | Directory | Command | Agents | Edit hook |', '|---|---|---|---|---|');
    for (const p of list) {
      out.push(`| ${p.display} | \`${p.configDir}\` | \`${placeholdersFor(p.provider).command_prefix}airtight\` | `
        + `${p.agentFormat === 'none' ? 'inline fallback' : p.agentFormat} | ${p.hooks ? 'yes' : 'no hook surface'} |`);
    }
    out.push('');
  }

  out.push('Every harness ships inline fallbacks for both sub-agents, including the ones that support '
    + 'sub-agents natively, because a user can decline them and the role still has to be runnable.');
  return out.join('\n');
}

function severityDoc() {
  const out = [
    '# Severity, confidence, and priority',
    '',
    'Three orthogonal axes. Collapsing them into one number forces a tool to rank an unproven '
      + 'catastrophe and a proven annoyance together, and the reader learns to distrust both.',
    '',
    '## Severity',
    '',
    'Exploitability times impact. Drives the remediation deadline.',
    '',
    '| Severity | SLA |',
    '|---|---|',
    ...SEVERITIES.map((s) => `| \`${s}\` | ${SLA_DAYS[s]} days |`),
    '',
    '## Confidence',
    '',
    '| Confidence | Means |',
    '|---|---|',
    '| `confirmed` | The pattern *is* the vulnerability, or the path was traced, or an exploit showed it. |',
    '| `firm` | Almost certainly real. A legitimate explanation exists but is rare. |',
    '| `tentative` | The dangerous shape is present. Reachability is unproven. |',
    '',
    '## Priority is derived',
    '',
    '| | ' + CONFIDENCES.join(' | ') + ' |',
    '|---|' + CONFIDENCES.map(() => '---').join('|') + '|',
    ...SEVERITIES.map((s) => `| **${s}** | ${CONFIDENCES.map((c) => priorityOf(s, c)).join(' | ')} |`),
    '',
    '**A tentative finding is never P0.** Dropping everything for something that might not be '
      + 'reachable is how a team learns to ignore P0.',
    '',
    'There is a test asserting this holds for every severity, and another asserting no rule in the '
      + 'immediate tier is `tentative` — that tier interrupts an edit, and confidence is what earns '
      + 'that, not severity.',
  ];
  return out.join('\n');
}

function main() {
  const rules = compileAll(JSON.parse(read('engine/build/rules.json')));
  const meta = JSON.parse(read('skill/scripts/command-metadata.json'));
  const skillSrc = read('skill/SKILL.src.md');

  write('rules.md', rulesDoc(rules));
  write('commands.md', commandsDoc(meta, skillSrc));
  write('harnesses.md', harnessesDoc());
  write('severity.md', severityDoc());

  console.log(`build-docs: rules.md (${rules.length} rules), commands.md, harnesses.md, severity.md`);
  return 0;
}

process.exit(main());
