#!/usr/bin/env node
// Bundle the engine into one dependency-free file.
//
// The shipped skill must run from a git clone with nothing installed, so the
// YAML parser the structured tiers need is inlined rather than required. This
// is the same approach impeccable takes with its browser bundle.

import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'skill', 'scripts', 'engine', 'airtight.mjs');

// The YAML parser ships a CommonJS build that calls require('process').
// esbuild cannot rewrite a dynamic require into an ESM import, so the bundle
// gets a real `require` built from its own URL. This is esbuild's documented
// interop shim, and it is preferred over aliasing to the package's ESM build
// because that would pin us to the package's internal file layout.
const BANNER = `// airtight engine — GENERATED by scripts/build-engine.mjs. Do not edit.
// Source of truth: engine/src/. Bundled so the shipped skill has no runtime
// dependencies and works from a plain git clone.
import { createRequire as __airtightCreateRequire } from 'node:module';
const require = __airtightCreateRequire(import.meta.url);`;

async function main() {
  mkdirSync(dirname(OUT), { recursive: true });

  await build({
    entryPoints: [join(ROOT, 'engine', 'src', 'cli.mjs')],
    outfile: OUT,
    bundle: true,
    platform: 'node',
    target: 'node20',
    format: 'esm',
    // Node builtins stay external; everything else is inlined.
    packages: 'bundle',
    external: ['node:*'],
    banner: { js: BANNER },
    legalComments: 'none',
    logLevel: 'warning',
  });

  // The rule bundle ships beside the engine, so the launcher can point at it
  // without the engine having to guess where the skill was installed.
  const rules = readFileSync(join(ROOT, 'engine', 'build', 'rules.json'), 'utf8');
  writeFileSync(join(ROOT, 'skill', 'scripts', 'rules.json'), rules);

  const kb = (p) => `${(statSync(p).size / 1024).toFixed(0)}kb`;
  console.log(`build-engine: ${OUT.replace(`${ROOT}/`, '')} (${kb(OUT)})`);
  console.log(`build-engine: skill/scripts/rules.json (${kb(join(ROOT, 'skill/scripts/rules.json'))})`);
}

main().catch((err) => {
  console.error(`build-engine: ${err.message}`);
  process.exit(1);
});
