#!/usr/bin/env node
// Run airtight against the deliberately vulnerable demo and record the result.
//
// The golden file is a regression test with a second job: it keeps the numbers
// in the README honest. A claim about what airtight catches that nobody
// re-derives is a claim that quietly stops being true.
//
//   node scripts/demo.mjs            print the run
//   node scripts/demo.mjs --write    update the golden
//   node scripts/demo.mjs --check    fail if the run drifted

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const APP = join(ROOT, 'demo', 'vulnerable-shop');
const GOLDEN = join(ROOT, 'demo', 'expected-findings.txt');
const MODE = process.argv.includes('--write') ? 'write'
  : process.argv.includes('--check') ? 'check' : 'print';

function scan(extra = []) {
  const r = spawnSync(process.execPath, [
    join(ROOT, 'engine/src/cli.mjs'), 'detect', '--no-config', ...extra, '.',
  ], {
    cwd: APP,
    encoding: 'utf8',
    env: { ...process.env, AIRTIGHT_RULES: join(ROOT, 'engine/build/rules.json') },
  });
  return { code: r.status, out: r.stdout ?? '' };
}

function summarize(text) {
  const rules = new Map();
  for (const [, rule] of text.matchAll(/^\s+L\d+ \[P\d\] (\S+)/gm)) {
    rules.set(rule, (rules.get(rule) ?? 0) + 1);
  }
  const packs = new Map();
  for (const [rule, n] of rules) {
    const pack = rule.split('/')[0];
    packs.set(pack, (packs.get(pack) ?? 0) + n);
  }
  const priorities = {};
  for (const [, p] of text.matchAll(/\[(P\d)\]/g)) priorities[p] = (priorities[p] ?? 0) + 1;
  return { rules, packs, priorities };
}

function render() {
  const full = scan();
  const immediate = scan(['--tier', 'immediate']);
  const { rules, packs, priorities } = summarize(full.out);

  const lines = [
    '# airtight against demo/vulnerable-shop',
    '',
    '# Generated by scripts/demo.mjs. Run `node scripts/demo.mjs --write` to update.',
    '# --no-config, so nothing is suppressed.',
    '',
    `total findings:   ${[...rules.values()].reduce((a, b) => a + b, 0)}`,
    `distinct rules:   ${rules.size}`,
    `by priority:      ${['P0', 'P1', 'P2', 'P3'].filter((p) => priorities[p]).map((p) => `${priorities[p]} ${p}`).join(', ')}`,
    `by pack:          ${[...packs].sort().map(([p, n]) => `${p}=${n}`).join(' ')}`,
    `exit code:        ${full.code}`,
    '',
    `immediate tier:   ${summarize(immediate.out).rules.size} distinct rules would interrupt an edit`,
    '',
    '## Rules that fired',
    '',
    ...[...rules].sort(([a], [b]) => a.localeCompare(b)).map(([r, n]) => `${String(n).padStart(3)}  ${r}`),
  ];
  return `${lines.join('\n')}\n`;
}

function main() {
  if (!existsSync(join(ROOT, 'engine/build/rules.json'))) {
    console.error('demo: no compiled rules. Run: npm run build:rules');
    return 1;
  }

  const current = render();

  if (MODE === 'write') {
    writeFileSync(GOLDEN, current);
    console.log(`demo: wrote ${GOLDEN.replace(`${ROOT}/`, '')}`);
    console.log(current.split('\n').slice(4, 12).join('\n'));
    return 0;
  }

  if (MODE === 'check') {
    if (!existsSync(GOLDEN)) { console.error('demo: no golden file; run --write'); return 1; }
    const expected = readFileSync(GOLDEN, 'utf8');
    if (expected === current) { console.log('demo: output matches the golden.'); return 0; }
    console.error('demo: output drifted from the golden.');
    // Show only the summary block; a full diff of 60 rule lines is noise.
    const head = (s) => s.split('\n').slice(4, 12).join('\n');
    console.error(`\n--- expected ---\n${head(expected)}\n\n--- actual ---\n${head(current)}`);
    console.error('\nIf the change is intended: node scripts/demo.mjs --write');
    return 1;
  }

  process.stdout.write(current);
  return 0;
}

process.exit(main());
